/**
 * Streamy — Local Player Manager
 *
 * Plays music locally via mpv with JSON IPC control.
 * The host machine outputs video+audio directly to its display and amplifier.
 * Remote devices act as controllers via the web UI.
 *
 * Display modes:
 *   • video         — mpv plays the YouTube video fullscreen with audio
 *   • visualization — audio waveform visualization generated by lavfi
 *   • karaoke       — visualization + synced subtitle overlay
 */
'use strict';

const { spawn, exec } = require('child_process');
const EventEmitter     = require('events');
const net              = require('net');
const fs               = require('fs');
const os               = require('os');
const path             = require('path');

// ─── Helpers ─────────────────────────────────────────────────────────────────
function getLocalIP() {
  try {
    const ifaces = os.networkInterfaces();
    for (const name of Object.keys(ifaces)) {
      for (const iface of ifaces[name]) {
        if (iface.family === 'IPv4' && !iface.internal) return iface.address;
      }
    }
  } catch {}
  return '127.0.0.1';
}

function safeText(str = '') {
  return String(str).replace(/['":;\\]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 80);
}

// ─── Player ──────────────────────────────────────────────────────────────────
class Player extends EventEmitter {
  constructor(options = {}) {
    super();
    this.displayMode = options.displayMode || 'video';
    this.width       = options.width       || 1920;
    this.height      = options.height      || 1080;

    // Platform-specific mpv config
    this.platform    = options.platform    || 'pc';
    this.maxHeight   = options.maxHeight   || 2160;
    this.mpvVO       = options.mpvVO       || '';
    this.mpvHwdec    = options.mpvHwdec    || 'auto-safe';
    this.mpvExtra    = options.mpvExtraArgs || [];

    this.mpvProc      = null;
    this.idleProc     = null;
    this.loadingProc  = null;
    this.ipcSocket    = null;
    this.ipcReady     = false;
    this.ipcBuffer    = '';
    this.currentTrack = null;
    this.cookieArgs   = [];

    this.state = {
      playing:  false,
      position: 0,
      duration: 0,
      volume:   options.volume || 80,
    };

    this.socketPath     = '/tmp/streamy-mpv.sock';
    this.titleFile      = path.join(os.tmpdir(), 'streamy-title.txt');
    this.artistFile     = path.join(os.tmpdir(), 'streamy-artist.txt');
    this.subtitleFile   = path.join(os.tmpdir(), 'streamy-lyrics.srt');
    this.qrImagePath    = path.join(os.tmpdir(), 'streamy-qr.png');
    this.idleImagePath  = path.join(os.tmpdir(), 'streamy-idle.png');
    this.loadingImgPath = path.join(os.tmpdir(), 'streamy-loading.png');

    this.ip   = getLocalIP();
    this.port = 3000;
  }

  // ── Public API ───────────────────────────────────────────────────────────────

  async init(port) {
    this.port = port;
    this.ip   = getLocalIP();

    try { fs.unlinkSync(this.socketPath); } catch {}

    await this._generateIdleScreen();
    await this._generateLoadingScreen();
    this._showIdleScreen();

    // Watchdog: detect stalled playback (mpv crashed silently)
    this._lastPosition = 0;
    this._stallCount   = 0;
    setInterval(() => {
      if (!this.state.playing || !this.currentTrack) {
        this._stallCount = 0;
        return;
      }
      if (this.state.position === this._lastPosition) {
        this._stallCount++;
        if (this._stallCount >= 3) {
          console.warn('[mpv] playback stalled — forcing recovery');
          this._stallCount = 0;
          this.emit('trackError', this.currentTrack);
        }
      } else {
        this._stallCount = 0;
      }
      this._lastPosition = this.state.position;
    }, 5000);

    console.log(`\n📺 Local display: mpv on ${this.displayMode} mode`);
    console.log(`   Remote URL:    http://${this.ip}:${this.port}/remote\n`);
  }

  setCookieArgs(args) {
    this.cookieArgs = args || [];
  }

  async playTrack(track) {
    if (!track) return;

    this.currentTrack  = track;
    this.state.playing  = true;
    this.state.position = 0;
    this.state.duration = track.duration || 0;

    this._writeOverlay(track);

    const url = `https://www.youtube.com/watch?v=${track.videoId}`;

    // ── Seamless transition: reuse running mpv via IPC loadfile ──
    // (Not supported in DRM mode — mpv can't reinitialise the DRM output)
    if (this.mpvVO !== 'drm' && this.mpvProc && this.mpvProc.exitCode === null && this.ipcReady) {
      const sent = this._sendIPC('loadfile', url, 'replace');
      if (sent) {
        this._stopIdle();
        // Unpause — mpv stays paused after keep-open + loadfile
        setTimeout(() => this._sendIPC('set_property', 'pause', false), 500);
        console.log('[mpv] loadfile →', track.title);
        this.emit('trackStart', track);
        return;
      }
      console.warn('[mpv] loadfile send failed, respawning');
    }

    // ── First track or recovery: full spawn ──
    console.log('[mpv] spawning new instance for:', track.title);

    // In DRM mode: show branded loading screen during track transition
    if (this.mpvVO === 'drm') {
      this._showLoadingScreen();
    }

    this._stopIdle();
    this._killMpv();

    try { fs.unlinkSync(this.socketPath); } catch {}

    const args = [
      '--fs', '--no-terminal', '--no-osc', '--no-input-default-bindings',
      `--input-ipc-server=${this.socketPath}`,
      `--volume=${this.state.volume}`,
      '--force-window=yes',
      // DRM mode: keep-open=no (can't use loadfile, need clean exit on EOF)
      // Other modes: keep-open=yes (loadfile reuse, EOF detected via IPC)
      `--keep-open=${this.mpvVO === 'drm' ? 'no' : 'yes'}`,
      `--hwdec=${this.mpvHwdec}`,
      '--profile=fast',
      ...this.mpvExtra,
    ];

    // Platform-specific video output
    if (this.mpvVO) args.push(`--vo=${this.mpvVO}`);

    // Pass yt-dlp cookie/auth args via mpv's ytdl-raw-options
    const ytdlOpts = this._buildYtdlOpts();
    if (ytdlOpts) args.push(`--ytdl-raw-options=${ytdlOpts}`);

    if (this.displayMode === 'visualization' && this.mpvVO !== 'drm') {
      // Audio-only with waveform visualization (not supported in DRM mode)
      args.push(
        '--ytdl-format=bestaudio[ext=webm]/bestaudio[ext=m4a]/bestaudio/best',
        `--lavfi-complex=[aid1]asplit=2[ao][a1];[a1]showwaves=s=${this.width}x${this.height}:mode=cline:r=30:colors=0x7c5af0@0.85|0x00d4aa@0.5:scale=cbrt,format=yuv420p[vo]`,
      );
    } else if (this.platform === 'pi5') {
      // Pi 5: force H.264 (avc1) for reliable hardware decoding, fallback to any codec
      args.push(`--ytdl-format=bestvideo[height<=${this.maxHeight}][vcodec^=avc1]+bestaudio/bestvideo[height<=${this.maxHeight}][vcodec^=hev]+bestaudio/bestvideo[height<=${this.maxHeight}]+bestaudio/best`);
    } else {
      // PC: best quality up to configured max, any codec
      args.push(`--ytdl-format=bestvideo[height<=${this.maxHeight}]+bestaudio/bestvideo+bestaudio/best`);
    }

    args.push(url);

    console.log('[mpv] spawn →', track.title);

    this.mpvProc = spawn('mpv', args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, DISPLAY: process.env.DISPLAY || ':0' },
    });

    let stderrBuf = '';
    this.mpvProc.stderr.on('data', d => {
      stderrBuf += d.toString();
      if (process.env.DEBUG) console.log('[mpv]', d.toString().trim().slice(0, 200));
    });

    this.mpvProc.stdout.on('data', () => {});

    // Exit handler:
    // DRM mode (keep-open=no): exit 0 = track ended normally, non-0 = error
    // Non-DRM (keep-open=yes): mpv only exits on crash/kill, EOF handled via IPC
    this.mpvProc.on('exit', (code, signal) => {
      this._disconnectIPC();
      if (signal === 'SIGTERM' || signal === 'SIGKILL') return;
      this.state.playing = false;
      if (this.mpvVO === 'drm' && code === 0) {
        console.log('[mpv] track ended (DRM exit 0)');
        this.emit('trackEnd');
      } else {
        console.error('[mpv] unexpected exit, code:', code);
        this.emit('trackError', this.currentTrack);
      }
    });

    this.mpvProc.on('error', err => {
      console.error('[mpv] spawn error:', err.message);
      this.emit('trackError', this.currentTrack);
    });

    // Wait for IPC socket and connect
    const ready = await this._waitForSocket(8000);
    if (ready) {
      await this._connectIPC();
    } else {
      console.warn('[mpv] IPC socket not ready — playback may still work without control');
    }

    // DRM mode: wait for mpv to render first frame, then hide loading screen and switch back
    if (this.mpvVO === 'drm') {
      await new Promise(r => setTimeout(r, 500));
      this._hideLoadingScreen();
      try { require('child_process').execSync('sudo chvt 1 2>/dev/null || true', { stdio: 'ignore', timeout: 2000 }); } catch {}
    }

    this.emit('trackStart', track);
  }

  pause() {
    this._sendIPC('set_property', 'pause', true);
    this.state.playing = false;
    this.emit('stateChange', this.state);
  }

  resume() {
    if (!this.currentTrack) return;
    const sent = this._sendIPC('set_property', 'pause', false);
    if (!sent) {
      // mpv is dead — respawn with current track
      console.warn('[mpv] resume failed, respawning');
      this.ipcReady = false;
      this.playTrack(this.currentTrack);
      return;
    }
    this.state.playing = true;
    this.emit('stateChange', this.state);
  }

  togglePlay() {
    if (this.state.playing) this.pause();
    else this.resume();
  }

  seek(position) {
    this._sendIPC('set_property', 'time-pos', position);
    this.state.position = position;
  }

  setVolume(vol) {
    this.state.volume = Math.max(0, Math.min(100, vol));
    this._sendIPC('set_property', 'volume', this.state.volume);
    this.emit('stateChange', this.state);
  }

  setDisplayMode(mode) {
    const old = this.displayMode;
    this.displayMode = (mode === 'karaoke') ? 'karaoke' : (mode === 'visualization') ? 'visualization' : 'video';
    if (this.displayMode !== old && this.currentTrack) {
      // Restart current track in new mode (brief interruption)
      this.playTrack(this.currentTrack);
    }
  }

  /** Load synced lyrics as SRT subtitles into mpv */
  loadLyrics(syncedLrc) {
    if (!syncedLrc || !this.ipcReady) return;
    try {
      const srt = this._lrcToSrt(syncedLrc);
      fs.writeFileSync(this.subtitleFile, srt);
      this._sendIPC('sub-add', this.subtitleFile);
      // Style: large, centered, with shadow
      this._sendIPC('set_property', 'sub-font-size', 52);
      this._sendIPC('set_property', 'sub-color', '#FFFFFF');
      this._sendIPC('set_property', 'sub-shadow-offset', 3);
      this._sendIPC('set_property', 'sub-shadow-color', '#000000AA');
    } catch (e) {
      console.warn('[mpv] subtitle load error:', e.message);
    }
  }

  /** Remove subtitle overlay from display */
  removeSubs() {
    this._sendIPC('sub-remove');
  }

  /**
   * Detect the audio start offset in a video.
   * Music videos often have a silent visual intro before the music begins.
   * LRC lyrics assume music starts at 0:00, so the offset = when audio actually starts.
   * Returns the timestamp in seconds, or 0 if audio starts immediately.
   */
  detectAudioStart(videoId) {
    return new Promise(resolve => {
      const url = `https://www.youtube.com/watch?v=${videoId}`;
      const timeout = setTimeout(() => {
        console.warn('[audio-detect] timed out');
        resolve(0);
      }, 25000);

      const ytdlpArgs = [
        ...this.cookieArgs,
        '-f', 'bestaudio',
        '-o', '-',
        '--no-warnings',
        url,
      ];

      // Detect silence at the start of the audio
      // Low threshold (-35dB) and short duration (0.2s) to catch the exact moment audio begins
      const ffmpegArgs = [
        '-i', 'pipe:0',
        '-t', '60',
        '-af', 'silencedetect=n=-35dB:d=0.2',
        '-f', 'null', '-',
      ];

      const ytdlp  = spawn('yt-dlp', ytdlpArgs, { stdio: ['ignore', 'pipe', 'ignore'] });
      const ffmpeg  = spawn('ffmpeg', ffmpegArgs, { stdio: ['pipe', 'ignore', 'pipe'] });

      ytdlp.stdout.pipe(ffmpeg.stdin);
      ytdlp.on('error', () => {});
      ffmpeg.stdin.on('error', () => {});

      let stderrBuf = '';
      ffmpeg.stderr.on('data', d => { stderrBuf += d.toString(); });

      ffmpeg.on('close', () => {
        clearTimeout(timeout);

        // Look for first silence_end — this is when audio starts
        const m = stderrBuf.match(/silence_end:\s*([\d.]+)/);
        if (m) {
          const audioStart = parseFloat(m[1]);
          // Only meaningful if there's a genuine intro (>0.5s silence)
          if (audioStart > 0.5 && audioStart < 30) {
            console.log(`[audio-detect] audio starts at ${audioStart.toFixed(2)}s`);
            resolve(audioStart);
          } else {
            console.log(`[audio-detect] audio starts at ${audioStart.toFixed(2)}s (negligible)`);
            resolve(0);
          }
        } else {
          // No silence detected — audio starts immediately
          console.log('[audio-detect] no leading silence — audio starts at 0');
          resolve(0);
        }
      });

      ffmpeg.on('error', () => {
        clearTimeout(timeout);
        resolve(0);
      });

      ytdlp.on('close', () => {
        try { ffmpeg.stdin.end(); } catch {}
      });
    });
  }

  stop() {
    if (this.mpvVO === 'drm') {
      this._showLoadingScreen();
    }
    this._killMpv();
    this.currentTrack   = null;
    this.state.playing  = false;
    this.state.position = 0;
    this.state.duration = 0;
    this._showIdleScreen();
    // Give idle mpv a moment to take DRM, then clean up loading screen
    if (this.mpvVO === 'drm') {
      setTimeout(() => this._hideLoadingScreen(), 1500);
    }
    this.emit('stateChange', this.state);
  }

  getStatus() {
    return {
      displayMode:  this.displayMode,
      currentTrack: this.currentTrack,
      state:        { ...this.state },
      ip:           this.ip,
      remoteUrl:    `http://${this.ip}:${this.port}/remote`,
    };
  }

  destroy() {
    this._killMpv();
    this._stopIdle();
    this._disconnectIPC();
  }

  // ── mpv IPC ──────────────────────────────────────────────────────────────────

  _buildYtdlOpts() {
    if (!this.cookieArgs.length) return '';
    const opts = [];
    for (let i = 0; i < this.cookieArgs.length; i++) {
      const arg = this.cookieArgs[i].replace(/^--/, '');
      if (i + 1 < this.cookieArgs.length && !this.cookieArgs[i + 1].startsWith('--')) {
        opts.push(`${arg}=${this.cookieArgs[i + 1]}`);
        i++;
      } else {
        opts.push(arg);
      }
    }
    return opts.join(',');
  }

  _waitForSocket(timeout = 5000) {
    return new Promise(resolve => {
      const start = Date.now();
      const check = () => {
        if (fs.existsSync(this.socketPath)) return resolve(true);
        if (Date.now() - start > timeout) return resolve(false);
        setTimeout(check, 150);
      };
      check();
    });
  }

  _connectIPC() {
    return new Promise(resolve => {
      try {
        this.ipcSocket = net.createConnection(this.socketPath);
        this.ipcBuffer = '';

        this.ipcSocket.on('connect', () => {
          this.ipcReady = true;
          this._sendIPC('observe_property', 1, 'time-pos');
          this._sendIPC('observe_property', 2, 'duration');
          this._sendIPC('observe_property', 3, 'pause');
          this._sendIPC('observe_property', 4, 'eof-reached');
          resolve();
        });

        this.ipcSocket.on('data', data => {
          this.ipcBuffer += data.toString();
          const lines = this.ipcBuffer.split('\n');
          this.ipcBuffer = lines.pop() || '';
          for (const line of lines) {
            if (!line.trim()) continue;
            try { this._handleIPCMessage(JSON.parse(line)); } catch {}
          }
        });

        this.ipcSocket.on('error', () => { this.ipcReady = false; resolve(); });
        this.ipcSocket.on('close', () => { this.ipcReady = false; });

        // Timeout if socket doesn't connect
        setTimeout(() => { if (!this.ipcReady) resolve(); }, 3000);
      } catch { resolve(); }
    });
  }

  _handleIPCMessage(msg) {
    if (msg.event === 'property-change') {
      if (msg.name === 'time-pos' && typeof msg.data === 'number') {
        this.state.position = msg.data;
        this.emit('timeUpdate', this.state.position, this.state.duration);
      } else if (msg.name === 'duration' && typeof msg.data === 'number') {
        this.state.duration = msg.data;
      } else if (msg.name === 'pause' && typeof msg.data === 'boolean') {
        this.state.playing = !msg.data;
        this.emit('stateChange', this.state);
      } else if (msg.name === 'eof-reached' && msg.data === true) {
        console.log('[mpv] eof-reached — track finished');
        this.emit('trackEnd');
      }
    } else if (msg.event === 'end-file') {
      console.log('[mpv] end-file reason:', msg.reason);
      if (msg.reason === 'eof') {
        this.emit('trackEnd');
      } else if (msg.reason === 'error') {
        this.emit('trackError', this.currentTrack);
      }
    }
  }

  _sendIPC(...args) {
    if (!this.ipcSocket || !this.ipcReady) return false;
    try { this.ipcSocket.write(JSON.stringify({ command: args }) + '\n'); return true; } catch { this.ipcReady = false; return false; }
  }

  _disconnectIPC() {
    if (this.ipcSocket) {
      try { this.ipcSocket.destroy(); } catch {}
      this.ipcSocket = null;
      this.ipcReady = false;
    }
  }

  // ── Process management ───────────────────────────────────────────────────────

  _killMpv() {
    this._disconnectIPC();
    if (this.mpvProc) {
      const proc = this.mpvProc;
      this.mpvProc = null;
      proc.removeAllListeners('exit');
      try { proc.kill('SIGTERM'); } catch {}
      setTimeout(() => { try { proc.kill('SIGKILL'); } catch {} }, 2000);
    }
  }

  // ── Idle screen ──────────────────────────────────────────────────────────────

  async _generateIdleScreen() {
    const remoteUrl = `http://${this.ip}:${this.port}/remote`;

    // Try QR code generation
    let hasQR = false;
    try {
      const QRCode = require('qrcode');
      await QRCode.toFile(this.qrImagePath, remoteUrl, {
        width: 300, margin: 2,
        color: { dark: '#ffffff', light: '#00000000' },
      });
      hasQR = true;
    } catch {
      console.warn('[player] qrcode package not found — run: npm install qrcode');
    }

    // Build idle image with ffmpeg
    const w = this.width, h = this.height;
    try {
      const filters = [];

      if (hasQR) {
        filters.push(
          `[1:v]scale=280:280[qr]`,
          `[0:v][qr]overlay=(W-w)/2:(H-h)/2-40[bg]`,
          `[bg]drawtext=text='Scan to add music':fontsize=32:fontcolor=white@0.9:x=(w-tw)/2:y=(h/2)+180:shadowcolor=black@0.5:shadowx=2:shadowy=2,` +
          `drawtext=text='${safeText(remoteUrl)}':fontsize=20:fontcolor=white@0.4:x=(w-tw)/2:y=(h/2)+230,` +
          `drawtext=text='Streamy':fontsize=64:fontcolor=0x7c5af0:x=(w-tw)/2:y=80:shadowcolor=black@0.8:shadowx=3:shadowy=3`
        );
      } else {
        filters.push(
          `[0:v]drawtext=text='Streamy':fontsize=64:fontcolor=0x7c5af0:x=(w-tw)/2:y=(h/2)-60:shadowcolor=black@0.8:shadowx=3:shadowy=3,` +
          `drawtext=text='${safeText(remoteUrl)}':fontsize=28:fontcolor=white@0.7:x=(w-tw)/2:y=(h/2)+30,` +
          `drawtext=text='Open this URL to add music':fontsize=22:fontcolor=white@0.4:x=(w-tw)/2:y=(h/2)+80`
        );
      }

      const inputArgs = ['-y', '-f', 'lavfi', '-i', `color=c=0x0a0a14:s=${w}x${h}:d=1`];
      if (hasQR) inputArgs.push('-i', this.qrImagePath);

      const cmd = ['ffmpeg', ...inputArgs, '-filter_complex', filters.join(';'), '-frames:v', '1', this.idleImagePath].map(a => `"${a}"`).join(' ');
      await this._run(cmd);
    } catch (e) {
      console.warn('[player] Idle screen generation failed:', e.message);
      // Create a minimal fallback via ffmpeg
      try {
        await this._run(`ffmpeg -y -f lavfi -i "color=c=0x0a0a14:s=${w}x${h}:d=1" -vf "drawtext=text='Streamy':fontsize=64:fontcolor=0x7c5af0:x=(w-tw)/2:y=(h-th)/2" -frames:v 1 "${this.idleImagePath}"`);
      } catch {}
    }
  }

  _showIdleScreen() {
    this._stopIdle();
    if (!fs.existsSync(this.idleImagePath)) return;

    const idleArgs = [
      '--fs', '--no-terminal', '--no-osc', '--no-input-default-bindings',
      '--image-display-duration=inf',
      '--force-window=yes',
      '--ao=null',
    ];
    if (this.mpvVO) idleArgs.push(`--vo=${this.mpvVO}`);
    idleArgs.push(this.idleImagePath);

    this.idleProc = spawn('mpv', idleArgs, {
      stdio: 'ignore',
      env: { ...process.env, DISPLAY: process.env.DISPLAY || ':0' },
    });

    this.idleProc.on('error', () => {});
    this.idleProc.on('exit', () => { this.idleProc = null; });
  }

  _stopIdle() {
    if (this.idleProc) {
      try { this.idleProc.kill('SIGTERM'); } catch {}
      this.idleProc = null;
    }
  }

  // ── Loading screen (DRM transition) ────────────────────────────────────────

  async _generateLoadingScreen() {
    const w = this.width, h = this.height;
    try {
      await this._run(`ffmpeg -y -f lavfi -i "color=c=0x0a0a14:s=${w}x${h}:d=1" -vf "drawtext=text='Streamy':fontsize=64:fontcolor=0x7c5af0:x=(w-tw)/2:y=(h/2)-60:shadowcolor=black@0.8:shadowx=3:shadowy=3,drawtext=text='Loading next track...':fontsize=28:fontcolor=white@0.5:x=(w-tw)/2:y=(h/2)+20" -frames:v 1 "${this.loadingImgPath}"`);
    } catch {
      // Fallback: simple dark screen
      try {
        await this._run(`ffmpeg -y -f lavfi -i "color=c=0x0a0a14:s=${w}x${h}:d=1" -frames:v 1 "${this.loadingImgPath}"`);
      } catch {}
    }
  }

  _showLoadingScreen() {
    if (this.mpvVO !== 'drm') return;
    if (!fs.existsSync(this.loadingImgPath)) return;
    try {
      // Kill any existing fbi
      this._hideLoadingScreen();
      // Display loading image on framebuffer (fbi works independently of DRM)
      this.loadingProc = spawn('fbi', [
        '--noverbose', '--autozoom', '--fitwidth',
        '-T', '7',
        this.loadingImgPath,
      ], { stdio: 'ignore' });
      this.loadingProc.on('error', () => { this.loadingProc = null; });
      this.loadingProc.on('exit', () => { this.loadingProc = null; });
      // Switch to VT7 where fbi is displaying
      require('child_process').execSync('sudo chvt 7 2>/dev/null || true', { stdio: 'ignore', timeout: 2000 });
    } catch {}
  }

  _hideLoadingScreen() {
    if (this.loadingProc) {
      try { this.loadingProc.kill('SIGTERM'); } catch {}
      this.loadingProc = null;
    }
    // Also kill any stale fbi processes
    try { require('child_process').execSync('killall fbi 2>/dev/null || true', { stdio: 'ignore' }); } catch {}
  }

  // ── Utilities ────────────────────────────────────────────────────────────────

  _writeOverlay(track) {
    try {
      fs.writeFileSync(this.titleFile,  safeText(track?.title  || 'Streamy'));
      fs.writeFileSync(this.artistFile, safeText(track?.artist || ''));
    } catch {}
  }

  /** Convert LRC synced lyrics to SRT subtitle format */
  _lrcToSrt(lrc) {
    const lines = lrc.split('\n').map(l => {
      const m = l.match(/^\[(\d{2}):(\d{2})\.(\d{2,3})\]\s*(.*)/);
      if (!m) return null;
      const ms = parseInt(m[3].padEnd(3, '0'));
      const secs = parseInt(m[1]) * 60 + parseInt(m[2]) + ms / 1000;
      return { time: secs, text: m[4].trim() };
    }).filter(Boolean).filter(l => l.text.length > 0);

    if (!lines.length) return '';

    let srt = '';
    for (let i = 0; i < lines.length; i++) {
      const start = lines[i].time;
      const end   = (i + 1 < lines.length) ? lines[i + 1].time : start + 5;
      srt += `${i + 1}\n${this._fmtSRT(start)} --> ${this._fmtSRT(end)}\n${lines[i].text}\n\n`;
    }
    return srt;
  }

  _fmtSRT(secs) {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = Math.floor(secs % 60);
    const ms = Math.floor((secs % 1) * 1000);
    return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')},${String(ms).padStart(3,'0')}`;
  }

  _run(cmd) {
    return new Promise((resolve, reject) => {
      exec(cmd, { timeout: 30000 }, err => err ? reject(err) : resolve());
    });
  }
}

module.exports = { Player, getLocalIP };
